name: FanTunes UI Test

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  ui-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ui

    steps:
      - name: Get FanTunes code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: npm
          cache-dependency-path: ui/package-lock.json

      - name: Install UI dependencies
        run: npm ci

      - name: Build FanTunes UI
        run: npm run build
